wandb_version: 1

activation:
  value: relu
batch_size:
  value: 128
epochs:
  value: 5
eta:
  value: 0.003936617818459283
hidden_size:
  value: 128
num_layers:
  value: 4
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: random
