wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 20
eta:
  value: 0.009704808196928084
hidden_size:
  value: 64
num_layers:
  value: 4
optimizer:
  value: adam
weight_decay:
  value: 0.0005
weight_init:
  value: he
