wandb_version: 1

activation:
  value: relu
batch_size:
  value: 128
epochs:
  value: 30
eta:
  value: 0.0045940081695639064
hidden_size:
  value: 64
num_layers:
  value: 5
optimizer:
  value: momentum
weight_decay:
  value: 0
weight_init:
  value: he
