wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
epochs:
  value: 30
eta:
  value: 0.0031122453956129404
hidden_size:
  value: 32
num_layers:
  value: 3
optimizer:
  value: momentum
weight_decay:
  value: 0.0005
weight_init:
  value: he
