wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
epochs:
  value: 20
eta:
  value: 0.005194525949367459
hidden_size:
  value: 64
num_layers:
  value: 3
optimizer:
  value: momentum
weight_decay:
  value: 0.0005
weight_init:
  value: he
