wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 32
epochs:
  value: 25
eta:
  value: 0.005631754089870468
hidden_size:
  value: 32
num_layers:
  value: 2
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: random
