wandb_version: 1

batch_size:
  value: 64
learning_rate:
  value: 2.6223740794639657e-05
model_type:
  value: EfficientNetV2
optimizer:
  value: sgd
trainable_layers:
  value: 2
weight_decay:
  value: 0.0006389886305356114
