wandb_version: 1

batch_size:
  value: 64
learning_rate:
  value: 8.60228264403004e-05
model_type:
  value: EfficientNetV2
optimizer:
  value: sgd
trainable_layers:
  value: 1
weight_decay:
  value: 9.542784056399626e-05
