wandb_version: 1

batch_size:
  value: 64
learning_rate:
  value: 0.0005888158890953578
model_type:
  value: EfficientNetV2
optimizer:
  value: adam
trainable_layers:
  value: 5
weight_decay:
  value: 0.0008713884398652137
