wandb_version: 1

batch_size:
  value: 32
learning_rate:
  value: 0.0001572152127336022
model_type:
  value: EfficientNetV2
optimizer:
  value: adam
trainable_layers:
  value: 2
weight_decay:
  value: 0.0006734111011964217
