wandb_version: 1

batch_size:
  value: 32
learning_rate:
  value: 0.000776134939002119
model_type:
  value: EfficientNetV2
optimizer:
  value: sgd
trainable_layers:
  value: 2
weight_decay:
  value: 0.00079588435158433
