wandb_version: 1

batch_size:
  value: 64
learning_rate:
  value: 0.00012305745988586226
model_type:
  value: EfficientNetV2
optimizer:
  value: adam
trainable_layers:
  value: 10
weight_decay:
  value: 0.0004828072441305128
