wandb_version: 1

activation:
  value: relu
batch_size:
  value: 128
epochs:
  value: 5
eta:
  value: 0.006032600499592685
hidden_size:
  value: 32
num_layers:
  value: 4
optimizer:
  value: adam
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
