_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
activation:
    value: Mish
batch_size:
    value: 64
data_augmentation:
    value: true
dropout_prob:
    value: 0.14701386796945703
img_size:
    value: 224
kernel_size:
    value:
        - 3
        - 3
        - 3
        - 3
        - 3
learning_rate:
    value: 0.000803211094432627
num_dense:
    value:
        - 512
num_filters:
    value:
        - 32
        - 64
        - 128
        - 256
        - 512
optimizer:
    value: adam
padding:
    value: 2
use_batchnorm:
    value: true
weight_decay:
    value: 0.0005326647274639
