_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 14
                - 17
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 32
learning_rate:
    value: 1.0003456077712924
model_type:
    value: EfficientNetV2
optimizer:
    value: sgd
trainable_layers:
    value: 5
weight_decay:
    value: 1.0000284130942456
