wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 16
data_augmentation:
  value: false
dropout_prob:
  value: 0.3
kernel_size:
  value:
  - 7
  - 7
  - 7
  - 7
  - 7
learning_rate:
  value: 0.0001
num_dense:
  value:
  - 256
num_filters:
  value:
  - 256
  - 128
  - 64
  - 32
  - 16
optimizer:
  value: sgd
padding:
  value: None
use_batchnorm:
  value: false
weight_decay:
  value: 0.0001
