wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 32
data_augmentation:
  value: false
dropout_prob:
  value: 0.3
kernel_size:
  value:
  - 5
  - 5
  - 5
  - 3
  - 3
learning_rate:
  value: 0.0001
num_dense:
  value:
  - 1024
  - 512
num_filters:
  value:
  - 32
  - 32
  - 32
  - 32
  - 32
optimizer:
  value: adam
padding:
  value: None
use_batchnorm:
  value: false
weight_decay:
  value: 0.0001
