wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 128
data_augmentation:
  value: false
dropout_prob:
  value: 0.3
kernel_size:
  value:
  - 3
  - 3
  - 3
  - 3
  - 3
learning_rate:
  value: 0.0001
num_dense:
  value:
  - 512
  - 256
num_filters:
  value:
  - 64
  - 64
  - 64
  - 64
  - 64
optimizer:
  value: adam
padding:
  value: None
use_batchnorm:
  value: false
weight_decay:
  value: 0.0001
