wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 64
data_augmentation:
  value: false
dropout_prob:
  value: 0.3
kernel_size:
  value:
  - 5
  - 5
  - 5
  - 5
  - 5
learning_rate:
  value: 0.0001
num_dense:
  value:
  - 1024
num_filters:
  value:
  - 32
  - 64
  - 128
  - 256
  - 512
optimizer:
  value: adam
padding:
  value: None
use_batchnorm:
  value: true
weight_decay:
  value: 0.0001
