wandb_version: 1

activation:
  value: SiLU
batch_size:
  value: 64
data_augmentation:
  value: true
dropout_prob:
  value: 0.061262994954476735
img_size:
  value: 224
kernel_size:
  value:
  - 3
  - 3
  - 3
  - 3
  - 3
learning_rate:
  value: 1.000344176737323
num_dense:
  value:
  - 512
num_filters:
  value:
  - 32
  - 64
  - 128
  - 256
  - 512
optimizer:
  value: adam
padding:
  value: 2
use_batchnorm:
  value: true
weight_decay:
  value: 1.0005772127915749
