wandb_version: 1

activation:
  value: sigmmoid
batch_size:
  value: 128
epochs:
  value: 40
eta:
  value: 0.004583542418051307
hidden_size:
  value: 32
num_layers:
  value: 4
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: random
