wandb_version: 1

activation:
  value: relu
batch_size:
  value: 128
epochs:
  value: 30
eta:
  value: 0.0007855625795677543
hidden_size:
  value: 128
num_layers:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
