wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 5
eta:
  value: 0.007911724291542974
hidden_size:
  value: 32
num_layers:
  value: 3
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: random
