wandb_version: 1

activation:
  value: SiLU
batch_size:
  value: 64
data_augmentation:
  value: true
dropout_prob:
  value: 0.4647602663729483
kernel_size:
  value:
  - 3
  - 3
  - 3
  - 3
  - 3
learning_rate:
  value: 1.000301580830204
num_dense:
  value:
  - 512
num_filters:
  value:
  - 32
  - 64
  - 128
  - 256
  - 512
optimizer:
  value: sgd
padding:
  value: 2
use_batchnorm:
  value: true
weight_decay:
  value: 1.0007636250336898
