wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 64
data_augmentation:
  value: true
dropout_prob:
  value: 0.3
img_size:
  value: 100
kernel_size:
  value:
  - 5
  - 5
  - 5
  - 5
  - 5
learning_rate:
  value: 0.0001
num_dense:
  value:
  - 512
num_filters:
  value:
  - 8
  - 16
  - 32
  - 256
  - 512
optimizer:
  value: adam
padding:
  value: None
use_batchnorm:
  value: true
weight_decay:
  value: 0.0001
