wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 128
data_augmentation:
  value: true
dropout_prob:
  value: 0.3
img_size:
  value: 100
kernel_size:
  value:
  - 5
  - 5
  - 5
  - 5
  - 5
learning_rate:
  value: 0.0001
num_dense:
  value:
  - 256
  - 128
num_filters:
  value:
  - 16
  - 32
  - 64
  - 128
  - 256
optimizer:
  value: adam
padding:
  value: None
use_batchnorm:
  value: true
weight_decay:
  value: 0.0001
