wandb_version: 1

activation:
  value: SiLU
batch_size:
  value: 64
data_augmentation:
  value: true
dropout_prob:
  value: 0.0365593751252794
img_size:
  value: 224
kernel_size:
  value:
  - 3
  - 3
  - 3
  - 3
  - 3
learning_rate:
  value: 0.0008705988393016838
num_dense:
  value:
  - 512
num_filters:
  value:
  - 32
  - 64
  - 128
  - 256
  - 512
optimizer:
  value: sgd
padding:
  value: 1
use_batchnorm:
  value: true
weight_decay:
  value: 0.0006009484496779649
