wandb_version: 1

activation:
  value: GELU
batch_size:
  value: 64
data_augmentation:
  value: true
dropout_prob:
  value: 0.38638108203714544
img_size:
  value: 224
kernel_size:
  value:
  - 3
  - 3
  - 3
  - 3
  - 3
learning_rate:
  value: 0.0003751361061209714
num_dense:
  value:
  - 512
num_filters:
  value:
  - 32
  - 64
  - 128
  - 256
  - 512
optimizer:
  value: sgd
padding:
  value: 2
use_batchnorm:
  value: true
weight_decay:
  value: 0.00028650083057640954
