wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 15
eta:
  value: 0.005451610209877319
hidden_size:
  value: 128
num_layers:
  value: 3
optimizer:
  value: rmsprop
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
