wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 15
eta:
  value: 0.00047425261327738394
hidden_size:
  value: 128
num_layers:
  value: 3
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: xavier
